# Basic

In [1]:
import numpy as np
import pandas as pd

In [2]:
space_data = {
    "Mission": ["Chandrayaan-3", "Gaganyaan", "Aditya-L1", "RISAT-2B"],
    "Type": ["Lunar", "Human Spaceflight", "Solar Study", "Surveillance"],
    "Country": ["India", "India", "India", "India"],
    "Status": ["Success", "Upcoming", "Ongoing", "Active"],
    "Budget (Cr)": [615, 10000, 400, 800]
}

In [3]:
df = pd.DataFrame(space_data)

In [4]:
print("🚀 Space Mission Data:")
df

🚀 Space Mission Data:

         Mission               Type Country    Status  Budget (Cr)
0  Chandrayaan-3              Lunar   India   Success          615
1      Gaganyaan  Human Spaceflight   India  Upcoming        10000
2      Aditya-L1        Solar Study   India   Ongoing          400
3       RISAT-2B       Surveillance   India    Active          800

In [5]:
df.to_csv('Space_data.csv')

In [6]:

print("\n✅ Successful Missions:")
print(df[df["Status"] == "Success"])


print("\n💰 Sorted by Budget:")
print(df.sort_values(by="Budget (Cr)", ascending=False))


print("\n📊 Average Budget:")
print(df["Budget (Cr)"].mean())

✅ Successful Missions:
         Mission   Type Country   Status  Budget (Cr)
0  Chandrayaan-3  Lunar   India  Success          615

💰 Sorted by Budget:
         Mission               Type Country    Status  Budget (Cr)
1      Gaganyaan  Human Spaceflight   India  Upcoming        10000
3       RISAT-2B       Surveillance   India    Active          800
0  Chandrayaan-3              Lunar   India   Success          615
2      Aditya-L1        Solar Study   India   Ongoing          400

📊 Average Budget:
2953.75

In [7]:
df.head(2)

         Mission               Type Country    Status  Budget (Cr)
0  Chandrayaan-3              Lunar   India   Success          615
1      Gaganyaan  Human Spaceflight   India  Upcoming        10000

In [8]:
df.tail(2)

     Mission          Type Country   Status  Budget (Cr)
2  Aditya-L1   Solar Study   India  Ongoing          400
3   RISAT-2B  Surveillance   India   Active          800

In [9]:
df.describe()

        Budget (Cr)
count      4.000000
mean    2953.750000
std     4700.342851
min      400.000000
25%      561.250000
50%      707.500000
75%     3100.000000
max    10000.000000